name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - run: java -version
    
    - name: Cache buck
      id: cache-buck
      uses: actions/cache@v2
      with:
        key: https://jitpack.io/com/github/airbnb/buck/f2865fec86dbe982ce1f237494f10b65bce3d270/buck-f2865fec86dbe982ce1f237494f10b65bce3d270-java11.pex
        path: tools/buck
    
    - name: Download buck
      run: make install_buck
      if: steps.cache-buck.outputs.cache-hit != 'true'
      
    - name: Download buck build artifacts
      uses: actions/download-artifact@v2
      with:
        name: buck-artifacts
        path: buck-out
      
    - name: Run tests
      run: make test
      
    - name: Upload buck build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: buck-artifacts
        path: buck-out
