name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - run: java -version
    
    - name: Cache buck
      id: cache-buck
      uses: actions/cache@v2
      with:
        key: https://jitpack.io/com/github/airbnb/buck/f2865fec86dbe982ce1f237494f10b65bce3d270/buck-f2865fec86dbe982ce1f237494f10b65bce3d270-java11.pex
        path: tools/buck
    
    - name: Download buck
      run: make install_buck
      if: steps.cache-buck.outputs.cache-hit != 'true'
      
    - name: Cache buck build artifacts
      uses: actions/cache@v2
      env:
        cache-name: cache-buck-out
      with:
        path: buck-out
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }} # Force cache miss so that build artifacts are always saved and restored
        restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-
      
    - name: Run tests
      run: make test
